---
# this configuration needs to correspond to the Vue.js frontends' vue.config.js devServer.proxy.target configuration!
# otherwise you may experience errors like: Proxy error: Could not proxy request /api/hello from localhost:8080 to http://localhost:8098... (ECONNREFUSED).
server:
  port: 10270
  servlet:
    context-path: /

spring:
#  main:
#    banner-mode: "off"
  mvc:
    servlet.path: /some_random_path

  security:
    user:
      name: admin
      password: nimda
  jersey:
    application-path: /
    servlet:
      load-on-startup: 1
#    type: filter
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

management:
  endpoint:
    health.enabled: true

endpoints:
  web:
    base-path: /actuator
    path-mapping.health: healthcheck

artifactId: cg-ms
